* Library Information
 Readme.org --- Communicate with ERC in different languages using google translate

 - Filename :: [[file:erc-babel.el][erc-babel.el]]
 - Description :: Communicate with ERC in different languages using google translate
 - Author :: Joe Bloggs <vapniks@yahoo.com>
 - Maintainer :: Joe Bloggs <vapniks@yahoo.com>
 - Copyleft (Ↄ) 2013, Joe Bloggs, all rites reversed.
 - Created :: 2013-05-13 18:23:24
 - Version :: 0.1
 - Last-Updated :: 2013-05-13 18:23:24
 -           By :: Joe Bloggs
 - URL :: https://github.com/vapniks/erc-babel
Keywords: 
 - Compatibility :: GNU Emacs 24.3.1
 - Package-Requires :: ((babel "") (erc "5.3"))

* Possible Dependencies

babel erc

* Commentary

Bitcoin donations gratefully accepted :: 199uU1gHyepvBmrQGyGdCWPCrqtZ6G4pbh

This library integrates babel (http://www.emacswiki.org/emacs/babel.el) with ERC 
(an emacs IRC client: http://www.emacswiki.org/cgi-bin/wiki/ERC) to provide automatic
translation of messages. It requires those two libraries are installed.
All sent and received messages will be translated if possible.
Different languages combinations can be set for different buffers, and translation can be toggled on or off.

It has been tested on emacs 23, with ERC version 5.3.

To toggle translation on/off (it is off by default) call `erc-babel-toggle'.

To set the languages to translate from and to for a particular buffer, call `erc-babel-set-languages'
The language combinations can be different for different buffers/channels.
To remember them between emacs sessions you could use session.el by Christopher Wedler 
(available here on marmalade: http://marmalade-repo.org/packages/session), and add `erc-babel-alist' to session-globals-include.
To remove translation for a particular buffer, set the from and to languages to the same value.

To include the original text with the translated message make sure `erc-babel-include-orig' is non-nil
This can be turned on/off by calling `erc-babel-include-orig-toggle'.

You can choose which webservice to use for doing the actual translation by customizing `erc-babel-backend' to
one of those listed. By default it uses Google, but you can change it if that doesn't work for you (check you 
have the latest version of babel.el)

You can also change the modeline display by customizing `erc-babel-modeline-type'. 
It shows you the languages being translated, and in which direction(s). 
By default it uses the full language names but you can change it to use short abbreviations.

You may also want to bind some keys in erc-mode like this:

(define-key erc-mode-map (kbd "C-c C-S-t") 'erc-babel-toggle)
(define-key erc-mode-map (kbd "C-c C-S-o") 'erc-babel-include-orig-toggle)

which can be put somewhere in your .emacs 
* Installation

 - Download the library from here, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'erc-babel) in your ~/.emacs file
